services:
  gd-dashboard:
    build: .
    container_name: vireon-cortex-app
    restart: unless-stopped
    ports:
      - "8505:8505"
    #env_file:
      #- .env.dockhand  # Tells Docker to load variables from your .env file
    deploy:
      resources:
        limits:
          memory: 1024M  # Hard limit (container will restart if it hits this)
        reservations:
          memory: 512M   # Soft limit (Docker tries to guarantee this much)
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
